export const QUOTES = [
    { text: "ทำวันนี้ เสร็จวันนี้ พรุ่งนี้จะได้สบาย", author: "ภูมิปัญญาไทย" },
    { text: "ความพยายามไม่เคยทรยศใคร ถึงแม้การบ้านจะเยอะแค่ไหน", author: "ภูมิปัญญาไทย" },
    { text: "รักชาติ ศาสน์ กษัตริย์ และรักการเรียน", author: "สุภาษิตไทย" },
    { text: "ไม้แก่ดัดยาก แต่ไม้เล็กดัดง่าย จงเรียนตอนนี้", author: "สุภาษิตไทย" },
    { text: "น้ำหยดลงหินทุกวัน หินยังกร่อน อย่าหยุดเรียน", author: "สุภาษิตไทย" },
    { text: "ความรู้ไม่เคยทำร้ายผู้แสวงหา", author: "ภูมิปัญญาไทย" },
    { text: "สอบได้ 100 คะแนน ไม่เท่ากับมีน้ำใจ 100 เปอร์เซ็นต์", author: "คำสอนในโรงเรียน" },
    { text: "อย่าบอกว่าไม่มีเวลา เพราะทุกคนมี 24 ชั่วโมงเท่ากัน", author: "ภูมิปัญญาไทย" },
    { text: "ศิลปะยืนยาว ชีวิตสั้น", author: "สมเด็จเจ้าฟ้าฯ กรมพระยานริศรานุวัดติวงศ์" },
    { text: "การเรียนรู้นั้นไม่รู้จักจบ รู้สิ่งใดไม่สู้รู้สิ่งนั้นให้แจ่มแจ้ง", author: "สมเด็จกรมพระยาดำรงราชานุภาพ" },
    { text: "วิชาความรู้เปรียบเหมือนอาวุธ ยิ่งรู้มากยิ่งมีพลัง", author: "สมเด็จกรมพระยาดำรงราชานุภาพ" },
    { text: "ถ้าท่านไม่อ่านหนังสือ ท่านจะรู้อะไร", author: "พระบาทสมเด็จพระจุลจอมเกล้าเจ้าอยู่หัว (ร.5)" },
    { text: "เวลามีค่า อย่าให้เสียเปล่า เรียนรู้ไว้ ใช้ให้เป็นประโยชน์", author: "พระบาทสมเด็จพระจุลจอมเกล้าเจ้าอยู่หัว (ร.5)" },
    { text: "จงรู้จักเสียสละเพื่อส่วนรวม เพราะส่วนรวมอยู่ได้ เราจึงอยู่ได้", author: "พระบาทสมเด็จพระจุลจอมเกล้าเจ้าอยู่หัว (ร.5)" },
    { text: "การเรียนเปรียบเหมือนการเดินเรือทวนน้ำ ถ้าไม่รุดหน้าก็ต้องถอยหลัง", author: "พระบาทสมเด็จพระมงกุฎเกล้าเจ้าอยู่หัว (ร.6)" },
    { text: "เวลาเปรียบเหมือนสายน้ำที่ไหลผ่าน เราต้องรีบเรียนรู้ก่อนที่มันจะผ่านพ้น", author: "พระบาทสมเด็จพระมงกุฎเกล้าเจ้าอยู่หัว (ร.6)" },
    { text: "ชาติจะดำรงอยู่ได้ด้วยความสามัคคี และความรู้ของคนในชาติ", author: "พระบาทสมเด็จพระมงกุฎเกล้าเจ้าอยู่หัว (ร.6)" },
    { text: "ทำดีได้ดี ทำชั่วได้ชั่ว เป็นของมีอยู่จริง อย่าสงสัย", author: "พระราชดำรัส ร.9" },
    { text: "การเรียนเปรียบเหมือนการเดินทางที่ไม่มีวันสิ้นสุด", author: "พระบาทสมเด็จพระบรมชนกาธิเบศร มหาภูมิพลอดุลยเดชมหาราช บรมนาถบพิตร (ร.9)" },
    { text: "ความจริงรู้ได้ยาก แต่ควรพยายามเรียนรู้", author: "พระบาทสมเด็จพระบรมชนกาธิเบศร มหาภูมิพลอดุลยเดชมหาราช บรมนาถบพิตร (ร.9)" },
    { text: "การรู้จักประมาณตนเป็นหนทางแห่งปัญญา", author: "พระบาทสมเด็จพระบรมชนกาธิเบศร มหาภูมิพลอดุลยเดชมหาราช บรมนาถบพิตร (ร.9)" },
    { text: "ช่วยกันคนละไม้คนละมือ เพื่อประโยชน์ของส่วนรวม", author: "พระบาทสมเด็จพระบรมชนกาธิเบศร มหาภูมิพลอดุลยเดชมหาราช บรมนาถบพิตร (ร.9)" },
    { text: "ความเพียรคือความสำเร็จ ความสำเร็จคือความเพียร", author: "พุทธทาสภิกขุ" },
    { text: "การศึกษาทำให้คนเจริญ ความไม่รู้ทำให้คนตกต่ำ", author: "พุทธทาสภิกขุ" },
    { text: "หน้าที่ของมนุษย์คือการทำหน้าที่ของตนให้ดีที่สุด", author: "พุทธทาสภิกขุ" },
    { text: "ธรรมะคือธรรมชาติ สอนให้เรารู้จักใช้ชีวิตอย่างถูกต้อง", author: "พุทธทาสภิกขุ" },
    { text: "รู้จักประมาณ รู้จักพอ รู้จักให้", author: "พระพรหมคุณาภรณ์ (ป.อ.ปยุตฺโต)" },
    { text: "สิ่งที่ทำวันนี้คือรากฐานของวันข้างหน้า", author: "พระพรหมคุณาภรณ์ (ป.อ.ปยุตฺโต)" },
    { text: "การศึกษาไม่ใช่แค่เรียนหนังสือ แต่คือการเรียนรู้ที่จะเป็นมนุษย์", author: "พระพรหมคุณาภรณ์ (ป.อ.ปยุตฺโต)" },
    { text: "เวลาที่เสียไป ไม่มีวันกลับคืน จงใช้ทุกนาทีให้เกิดประโยชน์", author: "พระพรหมคุณาภรณ์ (ป.อ.ปยุตฺโต)" },
    { text: "เวลาเป็นของมีค่า จงใช้ทุกนาทีให้เป็นประโยชน์", author: "สุนทรภู่" },
    { text: "ถึงอย่างไรก็ตาม วิชาหากินนั้นสำคัญกว่า", author: "สุนทรภู่" },
    { text: "รู้สิ่งใดไม่สู้รู้วิชา รู้รักษาตัวรอดเป็นยอดดี", author: "สุนทรภู่" },
    { text: "เกิดเป็นคนต้องมีวิชา จึงจะพาตัวรอดในสังคม", author: "สุนทรภู่" },
    { text: "หนทางแห่งความรู้นั้นไม่มีจุดสิ้นสุด", author: "สมเด็จพระมหาสมณเจ้า กรมพระยาวชิรญาณวโรรส" },
    { text: "ไม่มีใครเก่งมาแต่เกิด ทุกคนต้องเรียน ต้องฝึกฝน", author: "สมเด็จพระญาณสังวร สมเด็จพระสังฆราช" },
    { text: "ผู้รู้ดี คือผู้ที่รู้จักใช้ความรู้ให้เป็นประโยชน์", author: "สมเด็จพระญาณสังวร สมเด็จพระสังฆราช" },
    { text: "การงานใดจะสำเร็จได้ ต้องมีความเพียรเป็นที่ตั้ง", author: "สมเด็จพระญาณสังวร สมเด็จพระสังฆราช" },
    { text: "การบ้านที่คั่งค้าง คืออุปสรรคแห่งปัญญา", author: "หลวงปู่มั่น ภูริทัตโต" },
    { text: "ความเพียรเป็นทางแห่งความสำเร็จ ถึงแม้จะช้าแต่ก็ถึง", author: "พระธรรมโกศาจารย์ (พุทธทาส)" },
    { text: "เรียนให้สนุก เล่นให้เป็น วิชาให้เกิดผล", author: "ครูใหญ่ในดวงใจ" },
    { text: "อย่าให้วันนี้ผ่านไปโดยไม่ได้เรียนรู้อะไร", author: "ครูภาษาไทย" },
    { text: "การบ้านคือของขวัญที่ครูให้เพื่อทดสอบตัวเอง", author: "นักเรียนรุ่นพี่" },
    { text: "การบ้านคือบันไดสู่อนาคตที่สดใส", author: "ครูไทย" },
    { text: "พรุ่งนี้ก็สายไปเสียแล้ว", author: "คำคมนักสู้" },

    { text: "การศึกษาคือเครื่องมือที่ทรงพลังที่สุดในการเปลี่ยนแปลงโลก", author: "Nelson Mandela" },
    { text: "ความสำเร็จที่ยิ่งใหญ่เริ่มต้นจากก้าวเล็กๆ เสมอ", author: "Lao Tzu" },
    { text: "การเดินทางหมื่นลี้เริ่มต้นด้วยก้าวเดียว", author: "Lao Tzu" },
    { text: "การชนะที่แท้คือการชนะใจตนเอง", author: "พระพุทธเจ้า" },
    { text: "ความอดทนคือการนำพาชีวิตไปสู่ความสำเร็จ", author: "พระพุทธเจ้า" },
    { text: "ผู้ชนะคือผู้ที่ชนะใจตนเอง ไม่ใช่ผู้อื่น", author: "สมเด็จพระนเรศวรมหาราช" },
    { text: "อย่าประมาทในการเรียน เพราะความรู้คือเกราะป้องกันชีวิต", author: "พ่อขุนรามคำแหงมหาราช" },
    { text: "ผู้ใดไม่เรียนรู้ ย่อมไม่รู้จักโลก", author: "พระไตรปิฎก" },
    { text: "การเรียนคือแสงสว่างแห่งชีวิต", author: "คำสอนชาวบ้าน" },
    { text: "คนจะเก่งต้องหมั่นเพียร คนจะดีต้องหมั่นเรียน", author: "สุภาษิตเด็ก" },
    { text: "อย่ารอให้โอกาสมา แต่จงสร้างโอกาสด้วยการเรียนรู้", author: "ครูสมัยใหม่" },
    { text: "ชีวิตคือการเรียนรู้ ไม่มีคำว่าแก่เกินเรียน", author: "คำคมชีวิต" },
    { text: "เก่งไม่พอ ต้องดีด้วย ดีไม่พอ ต้องมีความรู้", author: "ครูปรัชญา" },
    { text: "สอบตกไม่ใช่จุดจบ แค่ต้องเริ่มใหม่และตั้งใจกว่าเดิม", author: "รุ่นพี่ให้กำลังใจ" },
    { text: "การบ้านคือสะพานสู่ความเข้าใจที่ลึกซึ้งยิ่งขึ้น", author: "นักการศึกษาไทย" },

    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
    { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "The mind is everything. What you think you become.", author: "Buddha" },
    { text: "Learning never exhausts the mind.", author: "Leonardo da Vinci" },
    { text: "The beautiful thing about learning is that nobody can take it away from you.", author: "B.B. King" },
    { text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
    { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
    { text: "The only person who is educated is the one who has learned how to learn and change.", author: "Carl Rogers" },
    { text: "Intelligence plus character — that is the goal of true education.", author: "Martin Luther King Jr." },
    { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
    { text: "The function of education is to teach one to think intensively and to think critically.", author: "Martin Luther King Jr." },
    { text: "Education is not preparation for life; education is life itself.", author: "John Dewey" },
    { text: "If you think education is expensive, try ignorance.", author: "Andy McIntyre" },
    { text: "Study hard, dream big.", author: "คำคมฮาร์วาร์ด" },
    { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
    { text: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
    { text: "Difficult roads often lead to beautiful destinations.", author: "Zig Ziglar" },
    { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
    { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
    { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "Well done is better than well said.", author: "Benjamin Franklin" },
    { text: "Education is the passport to the future, for tomorrow belongs to those who prepare for it today.", author: "Malcolm X" },
    { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
    { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
    { text: "The more that you read, the more things you will know.", author: "Dr. Seuss" },
    { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { text: "Shoot for the moon. Even if you miss, you'll land among the stars.", author: "Norman Vincent Peale" },
    { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
    { text: "He who opens a school door, closes a prison.", author: "Victor Hugo" },
    { text: "The whole purpose of education is to turn mirrors into windows.", author: "Sydney J. Harris" },
]
