export const QUOTES = [
    { text: "การบ้านแค่ 1 ชิ้น แต่อนาคตอีกยาวไกล", author: "HomeworkBot" },
    { text: "ทำวันนี้ เสร็จวันนี้ พรุ่งนี้จะได้สบาย", author: "ภูมิปัญญาไทย" },
    { text: "คนเก่งเขาไม่ใช่คนที่ทำถูกเสมอไป แต่เป็นคนที่ไม่ยอมแพ้", author: "HomeworkBot" },
    { text: "การบ้านไม่เคยทำร้ายใคร แต่มันอาจทำร้ายเกรดถ้าไม่ทำ", author: "HomeworkBot" },
    { text: "อย่าเพิ่งท้อถอย ถ้ายังไม่ถึงเส้นชัย แค่นั่งพักก่อนก็ได้", author: "HomeworkBot" },
    { text: "การบ้าน = การฝึกฝน ยิ่งทำยิ่งเก่ง", author: "HomeworkBot" },
    { text: "สอบได้ 0 คะแนนก็ไม่เป็นไร แค่เริ่มใหม่วันนี้", author: "HomeworkBot" },
    { text: "ความพยายามไม่เคยทรยศใคร ถึงแม้การบ้านจะเยอะแค่ไหน", author: "ภูมิปัญญาไทย" },
    { text: "เริ่มต้นวันนี้ดีกว่าเสียใจวันหน้า", author: "HomeworkBot" },
    { text: "ไม่มีอะไร impossible ถ้าเรายังไม่หยุดพยายาม", author: "HomeworkBot" },
    { text: "การบ้าน 1 ข้อที่ทำวันนี้ = คะแนน 1 แต้มในวันสอบ", author: "HomeworkBot" },
    { text: "อย่ากลัวที่จะเริ่ม เพราะทุกก้าวคือความก้าวหน้า", author: "HomeworkBot" },
    { text: "หนังสือคือเพื่อนที่ดีที่สุดในห้องสอบ", author: "HomeworkBot" },
    { text: "ถ้าเหนื่อยก็พักได้ แต่อย่าหยุด", author: "HomeworkBot" },
    { text: "คนที่ประสบความสำเร็จคือคนที่ลุกขึ้นมาทำการบ้านแม้จะขี้เกียจ", author: "HomeworkBot" },
    { text: "ไฟในตัวคุณสำคัญกว่าไฟในโทรศัพท์", author: "HomeworkBot" },
    { text: "การบ้านไม่ใช่ภาระ แต่เป็นโอกาสที่จะเรียนรู้", author: "HomeworkBot" },
    { text: "ความสำเร็จเล็กๆ น้อยๆ วันนี้ = พื้นฐานของความสำเร็จใหญ่ในวันหน้า", author: "HomeworkBot" },
    { text: "เธอเก่งกว่าเมื่อวานแน่นอน ถ้าวันนี้ยังคงทำการบ้าน", author: "HomeworkBot" },
    { text: "สอบตกไม่ใช่จุดจบของโลก แค่ต้องกลับมาทำการบ้านเพิ่ม", author: "HomeworkBot" },
    { text: "ความขี้เกียจเป็นอุปสรรคที่ใหญ่ที่สุดของนักเรียนไทย", author: "HomeworkBot" },
    { text: "การบ้านเยอะ = เนื้อหาเยอะ = ความรู้นายแน่น", author: "HomeworkBot" },
    { text: "ไม่ต้องเก่งที่สุด แค่ดีกว่ามื่อวานก็พอ", author: "HomeworkBot" },
    { text: "แรงบันดาลใจอยู่ที่ปลายปากกา", author: "HomeworkBot" },
    { text: "ถ้ายังไม่เริ่มทำตอนนี้ก็ไม่รู้จะเริ่มเมื่อไหร่", author: "HomeworkBot" },
    { text: "ข้อสอบไม่ใช่การทรมาน แต่เป็นการวัดว่าทำการบ้านมาดีแค่ไหน", author: "HomeworkBot" },
    { text: "รักการบ้าน = รักตัวเอง = รักอนาคต", author: "HomeworkBot" },
    { text: "ปิด TikTok แล้วเปิดหนังสือ", author: "HomeworkBot" },
    { text: "ความสำเร็จของวันนี้ = การบ้านที่ทำเมื่อวาน", author: "HomeworkBot" },
    { text: "แค่ 30 นาทีกับการบ้านวันนี้ = พรุ่งนี้สบายขึ้น 100%", author: "HomeworkBot" },
    { text: "ไม่มีใครเก่งตั้งแต่เกิด ทุกคนล้วนผ่านการบ้านมาก่อนทั้งนั้น", author: "HomeworkBot" },
    { text: "อย่าลืมให้รางวัลตัวเองหลังจากทำการบ้านเสร็จ", author: "HomeworkBot" },
    { text: "ชิ้นเดียวก็ยังดีกว่าไม่ทำเลย สู้ๆ", author: "HomeworkBot" },
    { text: "สอบเสร็จเมื่อไหร่ เจอเพื่อนเมื่อนั้น ไปเที่ยวกัน", author: "HomeworkBot" },
    { text: "วันนี้ขี้เกียจ พรุ่งนี้งานถาโถม อย่าปล่อยไว้", author: "HomeworkBot" },

    { text: "ศิลปะยืนยาว ชีวิตสั้น", author: "สมเด็จเจ้าฟ้าฯ กรมพระยานริศรานุวัดติวงศ์" },
    { text: "การเรียนรู้นั้นไม่รู้จักจบ รู้สิ่งใดไม่สู้รู้สิ่งนั้นให้แจ่มแจ้ง", author: "สมเด็จกรมพระยาดำรงราชานุภาพ" },
    { text: "วิชาความรู้เปรียบเหมือนอาวุธ ยิ่งรู้มากยิ่งมีพลัง", author: "สมเด็จกรมพระยาดำรงราชานุภาพ" },
    { text: "ทำดีได้ดี ทำชั่วได้ชั่ว เป็นของมีอยู่จริง อย่าสงสัย", author: "พระราชดำรัส ร.9" },
    { text: "ความเพียรคือความสำเร็จ ความสำเร็จคือความเพียร", author: "พุทธทาสภิกขุ" },
    { text: "การศึกษาทำให้คนเจริญ ความไม่รู้ทำให้คนตกต่ำ", author: "พุทธทาสภิกขุ" },
    { text: "รู้จักประมาณ รู้จักพอ รู้จักให้", author: "พระพรหมคุณาภรณ์ (ป.อ.ปยุตฺโต)" },
    { text: "สิ่งที่ทำวันนี้คือรากฐานของวันข้างหน้า", author: "พระพรหมคุณาภรณ์ (ป.อ.ปยุตฺโต)" },
    { text: "เวลาเป็นของมีค่า จงใช้ทุกนาทีให้เป็นประโยชน์", author: "สุนทรภู่" },
    { text: "ถึงอย่างไรก็ตาม วิชาหากินนั้นสำคัญกว่า", author: "สุนทรภู่" },
    { text: "รักชาติ ศาสน์ กษัตริย์ และรักการเรียน", author: "สุภาษิตไทย" },
    { text: "ไม้แก่ดัดยาก แต่ไม้เล็กดัดง่าย จงเรียนตอนนี้", author: "สุภาษิตไทย" },
    { text: "น้ำหยดลงหินทุกวัน หินยังกร่อน อย่าหยุดเรียน", author: "สุภาษิตไทย" },
    { text: "การบ้านคือบันไดสู่อนาคตที่สดใส", author: "ครูไทย" },
    { text: "ความรู้ไม่เคยทำร้ายผู้แสวงหา", author: "ภูมิปัญญาไทย" },
    { text: "สอบได้ 100 คะแนน ไม่เท่ากับมีน้ำใจ 100 เปอร์เซ็นต์", author: "คำสอนในโรงเรียน" },
    { text: "หนทางแห่งความรู้นั้นไม่มีจุดสิ้นสุด", author: "สมเด็จพระมหาสมณเจ้า กรมพระยาวชิรญาณวโรรส" },
    { text: "การศึกษาคือเครื่องมือที่ทรงพลังที่สุดในการเปลี่ยนแปลงโลก", author: "Nelson Mandela" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
]
